repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        pass_filenames: false
        entry: uvx ruff check --fix
      - id: format
        name: format
        language: system
        pass_filenames: false
        entry: uvx ruff format
      - id: pyright
        name: pyright
        language: system
        pass_filenames: false
        entry: uv run pyright
      - id: mypy
        name: mypy
        language: system
        pass_filenames: false
        entry: uv run mypy awscrt-stubs
      - id: istub
        name: istub
        language: system
        pass_filenames: false
        entry: uv run istub
      - id: sanity
        name: sanity
        language: system
        pass_filenames: false
        entry: ./scripts/sanity_check.sh
